### PR TITLE
Optimize the direct reporting to Chef Compliance

### LINKED ISSUE #45: Report to Chef Compliance directly
### Cookbook version

0.8.0

### Scenario:

User want to use a api token for Chef Compliance and report to compliance directly instead of sending the data via the Chef Server

### LINKED ISSUE #52: Reports are not displayed in Chef Compliance
### Cookbook version
0.8.0

### Chef-client version
no client

### Platform Details
MacOS 10.11.4

### Scenario:
I want to see the reports of the audit cookbook run in Chef Compliance.

### Steps to Reproduce:
Just run the audit cookbook and see if the reports are generated in Chef Compliance (Compliance only, no Chef Server)

### Expected Result:
List of reports

### Actual Result:
The path is misconfigured in the helper.rb when report.rb calls the construct_url method.

`#<URI::HTTPS:0x00000005076318 URL:https://172.28.128.4/api/owners/base/compliance/windows/tarowners/cjohannsen/inspec>`

That´s because the server.value is still set from the profile.rb run.

### PR DESCRIPTION
**Pull request by chris-rock**
### Description

This PR improves the support for direct reporting to Chef Compliance

### Issues Resolved

fixes #45
fixes #52

### CODE REVIEW

File: libraries/report.rb [hunk 1]
```diff
@@ -7,8 +7,8 @@ class ComplianceReport < Chef::Resource
 
   property :name, String, name_property: true
 
-  # to use a chef-compliance server that is _not_ "colocated" with chef-server
-  property :server, [URI, nil]
+  # to use a chef-compliance server that is used with chef-server integration
+  property :server, [String, URI, nil]
   property :port, Integer
   property :token, [String, nil]
   property :variant, String, default: 'chef' # 'chef', 'compliance'
```
Comment (jeremymv2) [inline libraries/report.rb]: With your very nice implementation `:variant` is no longer needed, correct?

Comment (chris-rock) [inline libraries/report.rb]: Yes, I want to get rid of variant

**Comment by jeremymv2** [comment]
👍 
Awesome improvements @chris-rock! This LGTM.

File: recipes/default.rb [hunk 2]
```diff
@@ -17,6 +17,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+# both are used if used with Chef Compliance directly, otherwise those should be nil
```
Comment (alexpop) [inline recipes/default.rb]: `used if used` jumped up here. Alternative:
`# These two attributes should only be set when connecting directly to Chef Compliance, otherwise they should be nil`

**Comment by alexpop** [comment]
Many thanks for the fixes and improvements Chris!

**Comment by cjohannsen81** [comment]
@chris-rock Hey, with the new version I have some 404 issues:

```
➜ cjo@Christians-MBP  ~/Downloads/chef-repo/cookbooks/atom git:(master) ✗ kitchen converge
-----> Starting Kitchen (v1.7.3)
-----> Converging <default-ubuntu-1404>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.2.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-ubuntu-1404>
       Starting Chef Client, version 12.10.24
       resolving cookbooks for run list: ["atom::default", "audit::default"]
       Synchronizing Cookbooks:
         - atom (0.1.1)
         - audit (0.9.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 2 resources
       Recipe: audit::default
         * compliance_profile[linux] action fetch
           * chef_gem[inspec] action install (up to date)
       [2016-05-26T08:01:53+00:00] WARN: Using inspec version: (0.22.1)
           - install/update inspec
           * directory[/tmp/kitchen/cache/compliance] action create (up to date)
           - create cache directory[2016-05-26T08:01:53+00:00] ERROR: Object does not exist on remote server.
       [2016-05-26T08:01:53+00:00] ERROR: 404 "Not Found"
       
           - fetch compliance profile
           * chef_gem[inspec] action install (up to date)
           * directory[/tmp/kitchen/cache/compliance] action create (up to date)
         
         * compliance_profile[linux] action execute
           * chef_gem[inspec] action install (up to date)
       [2016-05-26T08:01:53+00:00] WARN: Using inspec version: (0.22.1)
           - install/update inspec
           * directory[/tmp/kitchen/cache/compliance] action create (up to date)
           - create/verify cache directory
           - execute compliance profile
           * chef_gem[inspec] action install (up to date)
           * directory[/tmp/kitchen/cache/compliance] action create (up to date)
           * file[/tmp/kitchen/cache/compliance/base_linux_report.json] action create
             - update content in file /tmp/kitchen/cache/compliance/base_linux_report.json from f00949 to abcf6a
             - suppressed sensitive resource
         
         * compliance_report[chef-server] action execute[2016-05-26T08:01:54+00:00] ERROR: Object does not exist on remote server.
       [2016-05-26T08:01:54+00:00] ERROR: 404 "Not Found"
       
           - report compliance profiles' results
       
       Running handlers:
       Running handlers complete
       Chef Client finished, 4/12 resources updated in 02 seconds
       Finished converging <default-ubuntu-1404> (0m5.66s).

```
